# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-default

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
  displayName: 'Restore Buget Packages'


- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
  displayName: 'Build projects'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
  displayName: 'Run Test'

- task: DotNetCoreCLI@2
  inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/CustomerApi.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'
      modifyOutputPath: false
  displayName: 'Publish CustomerApi'